Resources:
  VPCB9E5F0B4:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: my_app_vpc
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/Resource
  VPCmyappvpcSubnet1Subnet38509E91:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: my_app_vpc
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: Ec2SimpleStack/VPC/my_app_vpcSubnet1
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet1/Subnet
  VPCmyappvpcSubnet1RouteTableDC2452C2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: Ec2SimpleStack/VPC/my_app_vpcSubnet1
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet1/RouteTable
  VPCmyappvpcSubnet1RouteTableAssociationEF05B702:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCmyappvpcSubnet1RouteTableDC2452C2
      SubnetId:
        Ref: VPCmyappvpcSubnet1Subnet38509E91
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet1/RouteTableAssociation
  VPCmyappvpcSubnet1DefaultRouteA5204E53:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCmyappvpcSubnet1RouteTableDC2452C2
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
    DependsOn:
      - VPCVPCGW99B986DC
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet1/DefaultRoute
  VPCmyappvpcSubnet2SubnetDA75AD9D:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: my_app_vpc
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: Ec2SimpleStack/VPC/my_app_vpcSubnet2
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet2/Subnet
  VPCmyappvpcSubnet2RouteTable5BDE9A2C:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      Tags:
        - Key: Name
          Value: Ec2SimpleStack/VPC/my_app_vpcSubnet2
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet2/RouteTable
  VPCmyappvpcSubnet2RouteTableAssociationF95C8614:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: VPCmyappvpcSubnet2RouteTable5BDE9A2C
      SubnetId:
        Ref: VPCmyappvpcSubnet2SubnetDA75AD9D
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet2/RouteTableAssociation
  VPCmyappvpcSubnet2DefaultRouteAC6DE16D:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: VPCmyappvpcSubnet2RouteTable5BDE9A2C
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: VPCIGWB7E252D3
    DependsOn:
      - VPCVPCGW99B986DC
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/my_app_vpcSubnet2/DefaultRoute
  VPCIGWB7E252D3:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: my_app_vpc
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/IGW
  VPCVPCGW99B986DC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPCB9E5F0B4
      InternetGatewayId:
        Ref: VPCIGWB7E252D3
    Metadata:
      aws:cdk:path: Ec2SimpleStack/VPC/VPCGW
  SecurityGroupDD263621:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh
      GroupName: my_app_sg
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow ssh access
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId:
        Ref: VPCB9E5F0B4
    Metadata:
      aws:cdk:path: Ec2SimpleStack/SecurityGroup/Resource
  InstanceInstanceRoleE9785DE5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: my_app_ec2
    Metadata:
      aws:cdk:path: Ec2SimpleStack/Instance/InstanceRole/Resource
  InstanceInstanceProfileAB5AEF02:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: InstanceInstanceRoleE9785DE5
    Metadata:
      aws:cdk:path: Ec2SimpleStack/Instance/InstanceProfile
  InstanceC1063A87:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      IamInstanceProfile:
        Ref: InstanceInstanceProfileAB5AEF02
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: t3.micro
      SecurityGroupIds:
        - Fn::GetAtt:
            - SecurityGroupDD263621
            - GroupId
      SubnetId:
        Ref: VPCmyappvpcSubnet1Subnet38509E91
      Tags:
        - Key: Name
          Value: my_app_ec2
      UserData:
        Fn::Base64: "#!/bin/bash"
    DependsOn:
      - InstanceInstanceRoleE9785DE5
    Metadata:
      aws:cdk:path: Ec2SimpleStack/Instance/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WOza6CQAyFn8X9UIXFjVvjwrgjcOPWlLHGKnTMTEdjCO8uCkpc9fTrzzkZ/C1gMcN7SOzhktRcQVsq2ovp0b4lm0G7u1qzPsouX5s8VjXbMlZC+mKTKlxU+seqpolPbBWCs4zKTr7LL7EVJd9vblDpjo/RZuxW2gc5NSRqSrLRsz423sXr2+AHbCUoih1fDrozjA20hRsSfepnnHt35Jq6zhQUXPTDcY4eG+ozvU/GQWfEHQjOYX5Ll5BmkM7OgTnxUZQbgmKoT8BOjhpLAQAA
    Metadata:
      aws:cdk:path: Ec2SimpleStack/CDKMetadata/Default
Parameters:
  SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2